- {id: 1, name: في أي سنة ولدت؟}
- {id: 2, name: ' آخر أربعة أحرف من رقم الضمان الاجتماعي؟'}
- {id: 3, name: ما هو الاسم الأوسط لوالدك؟}
- {id: 4, name: ما هو اسم أول مدرسة ذهبت إليها؟}
- {id: 5, name: من هو بطل طفولتك؟}
- {id: 6, name: ما هو وقت التسلية المفضل لديك؟}
- {id: 7, name: ما هو الفريق الرياضي المفضل لديك على الإطلاق؟}
- {id: 8, name: ما هو اسم جالب الحظ الخاص بك في أيام مدرستك الثانوية؟}
- {id: 9, name: ما هو طراز أول سيارة أو دراجة تملكتها؟}
- {id: 10, name: ما هو اسم حيوانك الأليف؟}
- {id: 11, name: ما هو الاسم الاوسط لوالدتك؟}
