- {id: 1, name: 'In welchem Jahr wurden Sie geboren?'}
- {id: 2, name: 'Letzte vier Ziffern der Sozialversicherungsnummer?'}
- {id: 3, name: 'Wie lautet der Mittelname Ihres Vaters?'}
- {id: 4, name: 'Wie hieß Ihre erste Schule?'}
- {id: 5, name: 'Wer war der Held Ihrer Kindheit?'}
- {id: 6, name: 'Was ist Ihre liebste Freizeitbeschäftigung?'}
- {id: 7, name: 'Was ist Ihre Lieblingsmannschaft?'}
- {id: 8, name: 'Was war das Maskottchen Ihrer Schule?'}
- {id: 9, name: 'Welche Marke war Ihr erstes Auto oder Fahrrad?'}
- {id: 10, name: 'Wie heißt Ihr Haustier?'}
- {id: 11, name: 'Wie lautet der Mittelname Ihrer Mutter?'}
