- {id: 1, name: 'באיזו שנה נולדת?'}
- {id: 2, name: 'ארבע הספרות האחרונות של SSN?'}
- {id: 3, name: 'מה שמו האמצעי של אביך?'}
- {id: 4, name: 'מה שמו של בית הספר הראשון בו למדת?'}
- {id: 5, name: 'מי היה גיבור הילדות שלך?'}
- {id: 6, name: 'מה הבילוי המועדף עליך?'}
- {id: 7, name: 'מה שם קבוצת הספורט שאתה אוהד?'}
- {id: 8, name: 'איזה קמע היה לך בימי תיכון?'}
- {id: 9, name: 'מה היה דגם הרכב או האופניים הראשונים שלך?'}
- {id: 10, name: 'מה שם חיית המחמד שלך?'}
- {id: 11, name: 'מהו שם הנעורים של אמך?'}
