- {id: 1, name: 'Melyik évben született?'}
- {id: 2, name: 'A TAJ-szám utolsó négy számjegye?'}
- {id: 3, name: 'Mi az édesapja középső neve?'}
- {id: 4, name: 'Mi volt az első iskolája neve?'}
- {id: 5, name: 'Ki volt a gyermekkori példaképe?'}
- {id: 6, name: 'Mi a kedvenc hobbija?'}
- {id: 7, name: 'Mi a legkedvesebb sportcsapata neve?'}
- {id: 8, name: 'Mi volt az óvodai jele?'}
- {id: 9, name: 'Milyen márkájú volt az első autója vagy motorkerékpárja?'}
- {id: 10, name: 'Mi a háziállata neve?'}
- {id: 11, name: 'Mi az édesanyja középső neve?'}
