- {id: 1, name: 生まれた年を入力してください。}
- {id: 2, name: SSNの最後の4桁を入力してください。}
- {id: 3, name: 父親のミドルネームは何ですか？}
- {id: 4, name: 最初に通った学校の名前を入力してください。}
- {id: 5, name: 子供の頃のヒーローを入力してください。}
- {id: 6, name: 趣味を入力してください。}
- {id: 7, name: お気に入りのスポーツチームを入力してください。}
- {id: 8, name: '高校時代のマスコットは何ですか?'}
- {id: 9, name: 最初に購入した車/バイクのメーカーを入力してください。}
- {id: 10, name: ペットの名前を入力してください。}
- {id: 11, name: '母親の旧姓は何ですか?'}
