- {id: 1, name: Podaj swój rok urodzenia}
- {id: 2, name: Podaj ostatnie cztery cyfry numeru ubezpieczenia społecznego.}
- {id: 3, name: 'Jak brzmi drugie imię Twojego ojca?'}
- {id: 4, name: 'Jak nazywała się Twoja pierwsza szkoła?'}
- {id: 5, name: 'Kto był Twoim dziecięcym bohaterem?'}
- {id: 6, name: 'Jaka jest Twoja ulubiona rozrywka?'}
- {id: 7, name: 'Jaka jest Twoja ulubiona drużyna?'}
- {id: 8, name: 'Jaka była maskotka Twojego liceum?'}
- {id: 9, name: 'Jakiej marki był Twój pierwszy samochód lub rower?'}
- {id: 10, name: 'Jak ma na imię Twój zwierzak?'}
- {id: 11, name: 'Jak brzmi drugie imię Twojej matki?'}
