- {id: 1, name: 'Bạn sinh năm nào?'}
- {id: 2, name: 'Bốn chữ số cuối cùng của SSN?'}
- {id: 3, name: 'Tên đệm của cha bạn là gì?'}
- {id: 4, name: 'Tên ngôi trường đầu tiên của bạn là gì?'}
- {id: 5, name: 'Ai là người anh hùng trong thời thơ ấu của bạn?'}
- {id: 6, name: 'Trò giải trí ưa thích của bạn là gì?'}
- {id: 7, name: 'Đội thể thao mà bạn luôn yêu thích là gì?'}
- {id: 8, name: 'Biểu tượng của trường trung học của bạn là gì?'}
- {id: 9, name: 'Nhãn hiệu của chiếc ô tô hay xe đạp đầu tiên của bạn là gì?'}
- {id: 10, name: 'Tên con vật nuôi của bạn là gì?'}
- {id: 11, name: 'Tên đệm của mẹ bạn là gì?'}
